# This is the config file for travis-ci for PINT

language: python

matrix:
    include:
        - python: "2.7"
        - python: "3.5"
        - python: "3.6"

sudo: required

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
    - pip install .

#script:
#    - pwd
#    - make test

script:
    - (cd tests ; nosetests -v --with-coverage --cover-package=pint --ignore-files=.\*DISABLED.py)

after_success:
    ( cd tests ; coveralls )
